In [1]:
import pandas as pd
# import matplotlib as plt
# from sklearn.datasets import make_blobs
import sklearn as skl
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# import tensorflow as tf
from pathlib import Path  
from sklearn.ensemble import RandomForestClassifier

In [2]:
mm_teams_merged_df = pd.read_csv("../../../Module 20 NCAA stats/mm_teams_merged.csv")
mm_teams_merged_df.head()

,Team,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,...,Conference_Pac-12,Conference_Patriot,Conference_SEC,Conference_SWAC,Conference_SoCon,Conference_Southland,Conference_Summit League,Conference_Sun Belt,Conference_WAC,Conference_WCC
0,A&M-Corpus Christi,44,141,343,156,90,349,100,51,200,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,Akron,278,177,162,70,119,192,272,64,22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Alabama,66,185,36,184,200,304,132,76,320,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Arizona,1,17,8,4,10,319,95,9,137,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Arkansas,116,110,71,218,58,323,32,89,145,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
mm_teams_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674 entries, 0 to 673
Data columns (total 53 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Team                        674 non-null    object
 1   Assists Per. Game Rank      674 non-null    int64
 2   Assist Turnover Ratio Rank  674 non-null    int64
 3   BlocksPerGame Rank          674 non-null    int64
 4   Field Goal % Rank           674 non-null    int64
 5   Field Goal % Defense Rank   674 non-null    int64
 6   Fouls Per Game Rank         674 non-null    int64
 7   Free Throw % Rank           674 non-null    int64
 8   Rebound Margin Rank         674 non-null    int64
 9   Scoring Defense Rank        674 non-null    int64
 10  Scoring Margin Rank         674 non-null    int64
 11  Scoring Offense Rank        674 non-null    int64
 12  Steals Per Game Rank        674 non-null    int64
 13  Three Pt FG Defense Rank    674 non-null    int64
 14  Three Pt FG % Rank          674 non-null    int64
 15  Three Pt FG Per Game Rank   674 non-null    int64
 16  Turnover Margin Rank        674 non-null    int64
 17  Turnover Per Game Rank      674 non-null    int64
 18  Win-Loss Rank               674 non-null    int64
 19  Tournament Wins             674 non-null    int64
 20  Conference_AAC              674 non-null    float64
 21  Conference_ACC              674 non-null    float64
 22  Conference_ASUN             674 non-null    float64
 23  Conference_America East     674 non-null    float64
 24  Conference_Atlantic 10      674 non-null    float64
 25  Conference_Big 12           674 non-null    float64
 26  Conference_Big East         674 non-null    float64
 27  Conference_Big Sky          674 non-null    float64
 28  Conference_Big South        674 non-null    float64
 29  Conference_Big Ten          674 non-null    float64
 30  Conference_Big West         674 non-null    float64
 31  Conference_C-USA            674 non-null    float64
 32  Conference_CAA              674 non-null    float64
 33  Conference_Horizon          674 non-null    float64
 34  Conference_Ivy League       674 non-null    float64
 35  Conference_MAAC             674 non-null    float64
 36  Conference_MAC              674 non-null    float64
 37  Conference_MEAC             674 non-null    float64
 38  Conference_MVC              674 non-null    float64
 39  Conference_Mountain West    674 non-null    float64
 40  Conference_NEC              674 non-null    float64
 41  Conference_None             674 non-null    float64
 42  Conference_OVC              674 non-null    float64
 43  Conference_Pac-12           674 non-null    float64
 44  Conference_Patriot          674 non-null    float64
 45  Conference_SEC              674 non-null    float64
 46  Conference_SWAC             674 non-null    float64
 47  Conference_SoCon            674 non-null    float64
 48  Conference_Southland        674 non-null    float64
 49  Conference_Summit League    674 non-null    float64
 50  Conference_Sun Belt         674 non-null    float64
 51  Conference_WAC              674 non-null    float64
 52  Conference_WCC              674 non-null    float64
dtypes: float64(33), int64(19), object(1)
memory usage: 279.2+ KB

In [4]:
def First_Wins(row):
    if row > 0:
        result = '1'
        
    else:
        result = '0'

    return result

mm_teams_merged_df['First_Round_Wins'] = mm_teams_merged_df['Tournament Wins'].apply(First_Wins)
mm_teams_merged_df.head()

,Team,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,...,Conference_Patriot,Conference_SEC,Conference_SWAC,Conference_SoCon,Conference_Southland,Conference_Summit League,Conference_Sun Belt,Conference_WAC,Conference_WCC,First_Round_Wins
0,A&M-Corpus Christi,44,141,343,156,90,349,100,51,200,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0
1,Akron,278,177,162,70,119,192,272,64,22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,Alabama,66,185,36,184,200,304,132,76,320,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,Arizona,1,17,8,4,10,319,95,9,137,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,Arkansas,116,110,71,218,58,323,32,89,145,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [5]:
def Second_Wins(row):
    if row > 1:
        result = '1'
    else:
        result = '0'
    return result

mm_teams_merged_df['Second_Round_Wins'] = mm_teams_merged_df['Tournament Wins'].apply(Second_Wins)
mm_teams_merged_df.head(3)

,Team,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,...,Conference_SEC,Conference_SWAC,Conference_SoCon,Conference_Southland,Conference_Summit League,Conference_Sun Belt,Conference_WAC,Conference_WCC,First_Round_Wins,Second_Round_Wins
0,A&M-Corpus Christi,44,141,343,156,90,349,100,51,200,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0
1,Akron,278,177,162,70,119,192,272,64,22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
2,Alabama,66,185,36,184,200,304,132,76,320,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0

In [6]:
def Third_Wins(row):
    if row > 2:
        result = '1'
    else:
        result = '0'
    return result

mm_teams_merged_df['Sweet_Sixteen_Wins'] = mm_teams_merged_df['Tournament Wins'].apply(Third_Wins)
mm_teams_merged_df.head(3)

,Team,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,...,Conference_SWAC,Conference_SoCon,Conference_Southland,Conference_Summit League,Conference_Sun Belt,Conference_WAC,Conference_WCC,First_Round_Wins,Second_Round_Wins,Sweet_Sixteen_Wins
0,A&M-Corpus Christi,44,141,343,156,90,349,100,51,200,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,0
1,Akron,278,177,162,70,119,192,272,64,22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
2,Alabama,66,185,36,184,200,304,132,76,320,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [7]:
def Fourth_Wins(row):
    if row > 3:
        result = '1'
    else:
        result = '0'
    return result

mm_teams_merged_df['Elite_Eight_Wins'] = mm_teams_merged_df['Tournament Wins'].apply(Fourth_Wins)
mm_teams_merged_df.head(10)

,Team,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,...,Conference_SoCon,Conference_Southland,Conference_Summit League,Conference_Sun Belt,Conference_WAC,Conference_WCC,First_Round_Wins,Second_Round_Wins,Sweet_Sixteen_Wins,Elite_Eight_Wins
0,A&M-Corpus Christi,44,141,343,156,90,349,100,51,200,...,0.0,1.0,0.0,0.0,0.0,0.0,0,0,0,0
1,Akron,278,177,162,70,119,192,272,64,22,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
2,Alabama,66,185,36,184,200,304,132,76,320,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
3,Arizona,1,17,8,4,10,319,95,9,137,...,0.0,0.0,0.0,0.0,0.0,0.0,1,1,0,0
4,Arkansas,116,110,71,218,58,323,32,89,145,...,0.0,0.0,0.0,0.0,0.0,0.0,1,1,1,0
5,Auburn,60,66,1,206,7,326,118,68,114,...,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0,0
6,Baylor,24,43,134,59,128,227,241,41,35,...,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0,0
7,Boise St.,292,236,136,147,148,170,338,45,13,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
8,Bryant,111,191,45,200,76,212,116,93,281,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
9,Cal St. Fullerton,299,253,330,146,211,119,20,141,96,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0

In [8]:
def Fifth_Wins(row):
    if row > 4:
        result = '1'
    else:
        result = '0'
    return result

mm_teams_merged_df['Final_Four_Wins'] = mm_teams_merged_df['Tournament Wins'].apply(Fifth_Wins)
mm_teams_merged_df.head(3)

,Team,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,...,Conference_Southland,Conference_Summit League,Conference_Sun Belt,Conference_WAC,Conference_WCC,First_Round_Wins,Second_Round_Wins,Sweet_Sixteen_Wins,Elite_Eight_Wins,Final_Four_Wins
0,A&M-Corpus Christi,44,141,343,156,90,349,100,51,200,...,1.0,0.0,0.0,0.0,0.0,0,0,0,0,0
1,Akron,278,177,162,70,119,192,272,64,22,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
2,Alabama,66,185,36,184,200,304,132,76,320,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0

In [9]:
def Sixth_Wins(row):
    if row > 5:
        result = '1'
    else:
        result = '0'
    return result

mm_teams_merged_df['Championship_Wins'] = mm_teams_merged_df['Tournament Wins'].apply(Sixth_Wins)
mm_teams_merged_df.head(30)

,Team,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,...,Conference_Summit League,Conference_Sun Belt,Conference_WAC,Conference_WCC,First_Round_Wins,Second_Round_Wins,Sweet_Sixteen_Wins,Elite_Eight_Wins,Final_Four_Wins,Championship_Wins
0,A&M-Corpus Christi,44,141,343,156,90,349,100,51,200,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
1,Akron,278,177,162,70,119,192,272,64,22,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
2,Alabama,66,185,36,184,200,304,132,76,320,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
3,Arizona,1,17,8,4,10,319,95,9,137,...,0.0,0.0,0.0,0.0,1,1,0,0,0,0
4,Arkansas,116,110,71,218,58,323,32,89,145,...,0.0,0.0,0.0,0.0,1,1,1,0,0,0
5,Auburn,60,66,1,206,7,326,118,68,114,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
6,Baylor,24,43,134,59,128,227,241,41,35,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
7,Boise St.,292,236,136,147,148,170,338,45,13,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
8,Bryant,111,191,45,200,76,212,116,93,281,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
9,Cal St. Fullerton,299,253,330,146,211,119,20,141,96,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
10,Chattanooga,179,86,319,48,121,223,76,37,39,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
11,Colgate,8,11,116,29,135,122,240,102,109,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
12,Colorado St.,91,22,187,16,167,44,16,208,77,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
13,Creighton,153,231,61,128,22,60,97,109,90,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
14,Davidson,69,14,257,15,104,112,53,85,76,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
15,Delaware,198,191,106,38,165,223,80,236,201,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
16,Duke,11,4,9,6,94,183,99,63,130,...,0.0,0.0,0.0,0.0,1,1,1,1,0,0
17,Georgia St.,138,96,44,336,93,42,156,161,67,...,0.0,1.0,0.0,0.0,0,0,0,0,0,0
18,Gonzaga,3,7,6,1,2,102,178,4,84,...,0.0,0.0,0.0,1.0,1,1,0,0,0,0
19,Houston,14,18,14,47,1,341,316,12,3,...,0.0,0.0,0.0,0.0,1,1,1,0,0,0
20,Illinois,41,60,193,125,62,196,207,31,115,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
21,Indiana,72,57,29,98,21,304,231,108,82,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
22,Iowa St.,67,148,181,230,133,333,284,230,21,...,0.0,0.0,0.0,0.0,1,1,0,0,0,0
23,Iowa,20,1,53,62,199,282,67,143,233,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
24,Jacksonville St.,86,131,214,42,48,34,279,62,116,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
25,Kansas,36,51,56,21,39,332,167,40,118,...,0.0,0.0,0.0,0.0,1,1,1,1,1,1
26,Kentucky,15,23,64,13,70,84,144,1,98,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
27,Longwood,77,84,297,113,184,126,136,18,68,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
28,Loyola Chicago,54,61,289,22,50,268,181,107,17,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0
29,LSU,188,291,60,192,6,339,120,116,30,...,0.0,0.0,0.0,0.0,0,0,0,0,0,0

In [10]:
round_advance_col = ['First_Round_Wins', 'Second_Round_Wins', 'Sweet_Sixteen_Wins', 'Elite_Eight_Wins', 'Final_Four_Wins', 'Championship_Wins']

In [11]:
# Define the features set.
X_rnd1 = mm_teams_merged_df.drop(columns= ["Team", "Tournament Wins", 'Second_Round_Wins', 'Sweet_Sixteen_Wins', 'Elite_Eight_Wins', 'Final_Four_Wins', 'Championship_Wins'])
X_rnd1.head()

,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,Scoring Margin Rank,...,Conference_Patriot,Conference_SEC,Conference_SWAC,Conference_SoCon,Conference_Southland,Conference_Summit League,Conference_Sun Belt,Conference_WAC,Conference_WCC,First_Round_Wins
0,44,141,343,156,90,349,100,51,200,77,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0
1,278,177,162,70,119,192,272,64,22,46,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,66,185,36,184,200,304,132,76,320,150,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,1,17,8,4,10,319,95,9,137,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,116,110,71,218,58,323,32,89,145,53,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [12]:
# Define the target set.
y_rnd1 = mm_teams_merged_df['First_Round_Wins']
y_rnd1.head()

0    0
1    0
2    0
3    1
4    1
Name: First_Round_Wins, dtype: object

X_train and y_train should remain the same every round?  Or should they change every round but be based on the actual win values?  X_test and y_test should change every round and should be changed to the round .

In [13]:
# Splitting into Train and Test sets.
X_train_rnd1, X_test_rnd1, y_train_rnd1, y_test_rnd1 = train_test_split(X_rnd1, y_rnd1, random_state=78)

In [14]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler_rnd1 = scaler.fit(X_train_rnd1)

# Scaling the data.
X_train_scaled_rnd1 = X_scaler_rnd1.transform(X_train_rnd1)
X_test_scaled_rnd1 = X_scaler_rnd1.transform(X_test_rnd1)

In [15]:
X_train_scaled_rnd1

array([[ 0.32275192, -1.05459901, -0.46796667, ..., -0.11855895,
        -0.17496355,  0.87506244],
       [ 0.70878338, -0.54908419, -1.30618511, ..., -0.11855895,
        -0.17496355,  0.87506244],
       [ 1.08275135,  1.0812011 , -0.88163292, ..., -0.11855895,
        -0.17496355, -1.1427756 ],
       ...,
       [ 0.56402158,  0.6515135 ,  0.88189159, ..., -0.11855895,
        -0.17496355,  0.87506244],
       [-0.12359695, -0.82711734,  2.35149535, ..., -0.11855895,
        -0.17496355,  0.87506244],
       [-0.67851718, -0.67546289,  1.16492639, ..., -0.11855895,
        -0.17496355, -1.1427756 ]])

In [16]:
# different step
# Create a random forest classifier. keep n_estimators between 64-128; 
# changing to 500 changes results very little
rf_model_rnd1 = RandomForestClassifier(n_estimators=128, random_state=78)

In [17]:
# Fitting the model
rf_model_rnd1 = rf_model_rnd1.fit(X_train_scaled_rnd1, y_train_rnd1)

In [18]:
# Making predictions using the testing data.
predictions_rnd1 = rf_model_rnd1.predict(X_test_scaled_rnd1)

In [19]:
predictions_rnd1

array(['0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '0', '1', '1',
       '0', '1', '1', '1', '1', '0', '0', '1', '1', '1', '1', '0', '0',
       '1', '0', '1', '1', '0', '0', '0', '1', '0', '0', '0', '0', '1',
       '1', '1', '0', '1', '0', '1', '1', '1', '1', '1', '0', '1', '0',
       '1', '0', '1', '1', '1', '1', '1', '0', '1', '0', '1', '1', '1',
       '0', '1', '0', '1', '0', '0', '0', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1',
       '0', '1', '1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1',
       '0', '1', '1', '1', '1', '0', '1', '1', '1', '0', '1', '0', '0',
       '1', '1', '1', '0', '0', '1', '0', '0', '1', '1', '1', '0', '0',
       '1', '1', '0', '1', '0', '0', '0', '0', '1', '1', '1', '0', '0',
       '0', '0', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '0',
       '1', '0', '0', '1', '0', '1', '0', '0', '1', '1', '0', '0', '0'],
      dtype=object)

In [20]:
predictions_rnd1.shape

(169,)

In [21]:
X_test_scaled_rnd1.shape

(169, 52)

In [22]:
X_test_scaled_rnd1

array([[ 2.51830584,  2.01640352,  0.0327872 , ..., -0.11855895,
        -0.17496355, -1.1427756 ],
       [ 2.28909966,  0.13336082,  0.58797084, ..., -0.11855895,
        -0.17496355, -1.1427756 ],
       [-0.1597874 , -0.35951613, -1.09935199, ..., -0.11855895,
        -0.17496355,  0.87506244],
       ...,
       [ 1.4808463 , -0.70073864, -0.47885263, ..., -0.11855895,
        -0.17496355, -1.1427756 ],
       [ 1.99957607,  1.99112777, -0.1087302 , ..., -0.11855895,
        -0.17496355, -1.1427756 ],
       [-0.71470762, -0.43534336,  1.80719766, ..., -0.11855895,
        -0.17496355, -1.1427756 ]])

figure out how to link predictions back to team names in original dataframe

In [23]:
# X_test['Prediction'] = predictions_rnd1
# X_test.head()
# mm_teams_merged_df['Predictions_Rnd1'] = predictions_rnd1
# mm_teams_merged_dfged_df.head()

In [24]:
# rnd1_df = mm_teams_merged_df
# rnd1_df.head()

In [25]:
# Calculating the confusion matrix.
cm_rnd1 = confusion_matrix(y_test_rnd1, predictions_rnd1)
# confusion_matrix(y_test, predictions).ravel()
# Create a DataFrame from the confusion matrix.
# cm_df = pd.DataFrame(
#     cm, index=["Actual 0", "Actual 1", "Actual 2", "Actual 3", "Actual 4", "Actual 5", "Actual 6"], columns=["Predicted 0", "Predicted 1", "Predicted 2","Predicted 3", "Predicted 4","Predicted 5", "Predicted 6"])
cm__rnd1_df = pd.DataFrame(
    cm_rnd1, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])
cm__rnd1_df
# cm
# true_negative, false_positive, false_negative, true_positive

          Predicted 0  Predicted 1
Actual 0           73            0
Actual 1            0           96

In [26]:
# Calculating the accuracy score.
acc_score_rnd1 = accuracy_score(y_test_rnd1, predictions_rnd1)

In [27]:
# Displaying results
print("Confusion Matrix Round 1")
# display(cm_df)
display(cm_rnd1)
print(f"Accuracy Score Round 1 : {acc_score_rnd1}")
print("Classification Report Round 1")
print(classification_report(y_test_rnd1, predictions_rnd1))

Confusion Matrix Round 1

array([[73,  0],
       [ 0, 96]], dtype=int64)

Accuracy Score Round 1 : 1.0
Classification Report Round 1
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        73
           1       1.00      1.00      1.00        96

    accuracy                           1.00       169
   macro avg       1.00      1.00      1.00       169
weighted avg       1.00      1.00      1.00       169

rnd1_df = mm_teams_merged_df['Predictions_Rnd1']
rnd1_df = drop all rows with 0 in Predictions_Rnd1 col.
predicted_winds_rnd1 needs to go back into dataframe and used to drop all predicted 0 rows = rnd1_df

rnd1_df  loaded into RFC model, split, trained, fit, predictions_rnd2, load predictions_rnd2 into rnd1_df = rnd2_df
rnd2_df = rnd2_df drop all rows with 0 in Prediction_Rnd2 col. 

rnd2_df  loaded into RFC model, split, trained, fit, predictions_rnd3, load predictions_rnd3 into rnd2_df = rnd3_df
rnd3_df = rnd3_df drop all rows with 0 in Prediction_Rnd3 col.

run importance_list.  Is this worthwhile, is it worth doing for each round?