In [1]:
import pandas as pd

In [2]:
data_df = pd.read_csv('/Users/bryanwenger/Desktop/Final_Project/March_Madness/Data_Creation/Bryan/mm_teams.csv')
data_df.head(10)

,Team,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,...,Scoring Offense Rank,Steals Per Game Rank,Three Pt FG Defense Rank,Three Pt FG % Rank,Three Pt FG Per Game Rank,Turnover Margin Rank,Turnover Per Game Rank,Win-Loss Rank,Tournament_Wins,Conference
0,A&M-Corpus Christi,44,141,343,156,90,349,100,51,200,...,45,26,56,190,266,44,296,75,0,Southland
1,Akron,278,177,162,70,119,192,272,64,22,...,187,251,228,78,131,162,63,51,0,MAC
2,Alabama,66,185,36,184,200,304,132,76,320,...,13,116,199,300,27,275,339,142,0,SEC
3,Arizona,1,17,8,4,10,319,95,9,137,...,3,147,139,95,139,232,110,2,2,Pac-12
4,Arkansas,116,110,71,218,58,323,32,89,145,...,50,72,125,320,279,40,287,36,3,SEC
5,Auburn,60,66,1,206,7,326,118,68,114,...,24,32,52,270,111,47,116,7,1,SEC
6,Baylor,24,43,134,59,128,227,241,41,35,...,41,18,32,148,111,20,156,12,1,Big 12
7,Boise St.,292,236,136,147,148,170,338,45,13,...,250,234,132,122,178,109,115,21,0,Mountain West
8,Bryant,111,191,45,200,76,212,116,93,281,...,28,175,77,318,90,288,285,62,0,NEC
9,Cal St. Fullerton,299,253,330,146,211,119,20,141,96,...,202,93,343,234,321,72,119,80,0,Big West

In [3]:
data_df.drop(columns=['Team', 'Conference'], inplace=True)
data_df.head()

,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,Scoring Margin Rank,Scoring Offense Rank,Steals Per Game Rank,Three Pt FG Defense Rank,Three Pt FG % Rank,Three Pt FG Per Game Rank,Turnover Margin Rank,Turnover Per Game Rank,Win-Loss Rank,Tournament_Wins
0,44,141,343,156,90,349,100,51,200,77,45,26,56,190,266,44,296,75,0
1,278,177,162,70,119,192,272,64,22,46,187,251,228,78,131,162,63,51,0
2,66,185,36,184,200,304,132,76,320,150,13,116,199,300,27,275,339,142,0
3,1,17,8,4,10,319,95,9,137,3,3,147,139,95,139,232,110,2,2
4,116,110,71,218,58,323,32,89,145,53,50,72,125,320,279,40,287,36,3

In [4]:
data_df.count()

Assists Per. Game Rank        674
Assist Turnover Ratio Rank    674
BlocksPerGame Rank            674
Field Goal % Rank             674
Field Goal % Defense Rank     674
Fouls Per Game Rank           674
Free Throw % Rank             674
Rebound Margin Rank           674
Scoring Defense Rank          674
Scoring Margin Rank           674
Scoring Offense Rank          674
Steals Per Game Rank          674
Three Pt FG Defense Rank      674
Three Pt FG % Rank            674
Three Pt FG Per Game Rank     674
Turnover Margin Rank          674
Turnover Per Game Rank        674
Win-Loss Rank                 674
Tournament_Wins               674
dtype: int64

In [5]:
y = data_df["Tournament_Wins"]
X = data_df.drop(columns="Tournament_Wins")

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(505, 18)

In [7]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=2000,
                                random_state=7)

In [8]:
classifier.fit(X_train, y_train)

/Users/bryanwenger/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(max_iter=2000, random_state=7)

In [9]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       0
1            1       2
2            0       1
3            0       0
4            1       2
5            0       2
6            1       0
7            0       1
8            0       1
9            1       2
10           0       0
11           0       0
12           0       0
13           0       0
14           1       0
15           0       0
16           1       3
17           0       2
18           0       0
19           0       1

In [10]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.38461538461538464

In [11]:
from sklearn.metrics import confusion_matrix, classification_report

In [12]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[55 13  4  0  0  1  0]
 [37  5  3  2  1  1  2]
 [ 8  8  2  2  1  1  0]
 [ 5  3  1  2  0  1  0]
 [ 2  0  0  3  0  0  0]
 [ 1  0  1  0  0  1  0]
 [ 0  1  1  0  0  1  0]]

In [13]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.51      0.75      0.61        73
           1       0.17      0.10      0.12        51
           2       0.17      0.09      0.12        22
           3       0.22      0.17      0.19        12
           4       0.00      0.00      0.00         5
           5       0.17      0.33      0.22         3
           6       0.00      0.00      0.00         3

    accuracy                           0.38       169
   macro avg       0.18      0.21      0.18       169
weighted avg       0.31      0.38      0.33       169

In [14]:
# Convert data frame in which tournament wins are binary 0=0 1-6=1
data_df.Tournament_Wins[data_df.Tournament_Wins == '1'] = 1
data_df.Tournament_Wins[data_df.Tournament_Wins == '2'] = 1
data_df.Tournament_Wins[data_df.Tournament_Wins == '3'] = 1
data_df.Tournament_Wins[data_df.Tournament_Wins == '4'] = 1
data_df.Tournament_Wins[data_df.Tournament_Wins == '5'] = 1
data_df.Tournament_Wins[data_df.Tournament_Wins == '6'] = 1
data_df.Tournament_Wins[data_df.Tournament_Wins == '0'] = 0
data_df.head(20)

,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,Scoring Margin Rank,Scoring Offense Rank,Steals Per Game Rank,Three Pt FG Defense Rank,Three Pt FG % Rank,Three Pt FG Per Game Rank,Turnover Margin Rank,Turnover Per Game Rank,Win-Loss Rank,Tournament_Wins
0,44,141,343,156,90,349,100,51,200,77,45,26,56,190,266,44,296,75,0
1,278,177,162,70,119,192,272,64,22,46,187,251,228,78,131,162,63,51,0
2,66,185,36,184,200,304,132,76,320,150,13,116,199,300,27,275,339,142,0
3,1,17,8,4,10,319,95,9,137,3,3,147,139,95,139,232,110,2,2
4,116,110,71,218,58,323,32,89,145,53,50,72,125,320,279,40,287,36,3
5,60,66,1,206,7,326,118,68,114,15,24,32,52,270,111,47,116,7,1
6,24,43,134,59,128,227,241,41,35,7,41,18,32,148,111,20,156,12,1
7,292,236,136,147,148,170,338,45,13,57,250,234,132,122,178,109,115,21,0
8,111,191,45,200,76,212,116,93,281,114,28,175,77,318,90,288,285,62,0
9,299,253,330,146,211,119,20,141,96,141,202,93,343,234,321,72,119,80,0
10,179,86,319,48,121,223,76,37,39,24,90,100,21,131,123,92,41,21,0
11,8,11,116,29,135,122,240,102,109,39,54,225,181,2,12,217,58,75,0
12,91,22,187,16,167,44,16,208,77,58,111,190,138,69,135,51,262,11,0
13,153,231,61,128,22,60,97,109,90,156,221,279,75,302,248,337,296,75,1
14,69,14,257,15,104,112,53,85,76,30,57,337,177,4,45,96,10,12,0
15,198,191,106,38,165,223,80,236,201,146,112,155,282,116,166,185,349,104,0
16,11,4,9,6,94,183,99,63,130,10,8,192,98,40,121,152,21,9,4
17,138,96,44,336,93,42,156,161,67,107,186,17,323,229,150,5,310,113,0
18,3,7,6,1,2,102,178,4,84,1,1,184,37,32,95,155,77,3,2
19,14,18,14,47,1,341,316,12,3,2,71,39,9,181,128,25,331,6,3

In [15]:
def First_Wins(row):


    if row > 0:


        result = '1'
        

    else:


        result = '0'


    return result


 


data_df['First_Round_Wins'] = data_df['Tournament_Wins'].apply(First_Wins)

In [16]:
data_df.head(10)

,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,Scoring Margin Rank,Scoring Offense Rank,Steals Per Game Rank,Three Pt FG Defense Rank,Three Pt FG % Rank,Three Pt FG Per Game Rank,Turnover Margin Rank,Turnover Per Game Rank,Win-Loss Rank,Tournament_Wins,First_Round_Wins
0,44,141,343,156,90,349,100,51,200,77,45,26,56,190,266,44,296,75,0,0
1,278,177,162,70,119,192,272,64,22,46,187,251,228,78,131,162,63,51,0,0
2,66,185,36,184,200,304,132,76,320,150,13,116,199,300,27,275,339,142,0,0
3,1,17,8,4,10,319,95,9,137,3,3,147,139,95,139,232,110,2,2,1
4,116,110,71,218,58,323,32,89,145,53,50,72,125,320,279,40,287,36,3,1
5,60,66,1,206,7,326,118,68,114,15,24,32,52,270,111,47,116,7,1,1
6,24,43,134,59,128,227,241,41,35,7,41,18,32,148,111,20,156,12,1,1
7,292,236,136,147,148,170,338,45,13,57,250,234,132,122,178,109,115,21,0,0
8,111,191,45,200,76,212,116,93,281,114,28,175,77,318,90,288,285,62,0,0
9,299,253,330,146,211,119,20,141,96,141,202,93,343,234,321,72,119,80,0,0

In [17]:
def Second_Wins(row):
    if row > 1:
        result = '1'
    else:
        result = '0'
    return result

data_df['Second_Round_Wins'] = data_df['Tournament_Wins'].apply(Second_Wins)
data_df.head(3)

,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,Scoring Margin Rank,...,Steals Per Game Rank,Three Pt FG Defense Rank,Three Pt FG % Rank,Three Pt FG Per Game Rank,Turnover Margin Rank,Turnover Per Game Rank,Win-Loss Rank,Tournament_Wins,First_Round_Wins,Second_Round_Wins
0,44,141,343,156,90,349,100,51,200,77,...,26,56,190,266,44,296,75,0,0,0
1,278,177,162,70,119,192,272,64,22,46,...,251,228,78,131,162,63,51,0,0,0
2,66,185,36,184,200,304,132,76,320,150,...,116,199,300,27,275,339,142,0,0,0

In [18]:
def Third_Wins(row):
    if row > 2:
        result = '1'
    else:
        result = '0'
    return result

data_df['Sweet_Sixteen_Wins'] = data_df['Tournament_Wins'].apply(Third_Wins)
data_df.head(3)

,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,Scoring Margin Rank,...,Three Pt FG Defense Rank,Three Pt FG % Rank,Three Pt FG Per Game Rank,Turnover Margin Rank,Turnover Per Game Rank,Win-Loss Rank,Tournament_Wins,First_Round_Wins,Second_Round_Wins,Sweet_Sixteen_Wins
0,44,141,343,156,90,349,100,51,200,77,...,56,190,266,44,296,75,0,0,0,0
1,278,177,162,70,119,192,272,64,22,46,...,228,78,131,162,63,51,0,0,0,0
2,66,185,36,184,200,304,132,76,320,150,...,199,300,27,275,339,142,0,0,0,0

In [19]:
def Fourth_Wins(row):
    if row > 3:
        result = '1'
    else:
        result = '0'
    return result

data_df['Elite_Eight_Wins'] = data_df['Tournament_Wins'].apply(Fourth_Wins)
data_df.head(10)

,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,Scoring Margin Rank,...,Three Pt FG % Rank,Three Pt FG Per Game Rank,Turnover Margin Rank,Turnover Per Game Rank,Win-Loss Rank,Tournament_Wins,First_Round_Wins,Second_Round_Wins,Sweet_Sixteen_Wins,Elite_Eight_Wins
0,44,141,343,156,90,349,100,51,200,77,...,190,266,44,296,75,0,0,0,0,0
1,278,177,162,70,119,192,272,64,22,46,...,78,131,162,63,51,0,0,0,0,0
2,66,185,36,184,200,304,132,76,320,150,...,300,27,275,339,142,0,0,0,0,0
3,1,17,8,4,10,319,95,9,137,3,...,95,139,232,110,2,2,1,1,0,0
4,116,110,71,218,58,323,32,89,145,53,...,320,279,40,287,36,3,1,1,1,0
5,60,66,1,206,7,326,118,68,114,15,...,270,111,47,116,7,1,1,0,0,0
6,24,43,134,59,128,227,241,41,35,7,...,148,111,20,156,12,1,1,0,0,0
7,292,236,136,147,148,170,338,45,13,57,...,122,178,109,115,21,0,0,0,0,0
8,111,191,45,200,76,212,116,93,281,114,...,318,90,288,285,62,0,0,0,0,0
9,299,253,330,146,211,119,20,141,96,141,...,234,321,72,119,80,0,0,0,0,0

In [20]:
def Fifth_Wins(row):
    if row > 4:
        result = '1'
    else:
        result = '0'
    return result

data_df['Final_Four_Wins'] = data_df['Tournament_Wins'].apply(Fifth_Wins)
data_df.head(3)

,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,Scoring Margin Rank,...,Three Pt FG Per Game Rank,Turnover Margin Rank,Turnover Per Game Rank,Win-Loss Rank,Tournament_Wins,First_Round_Wins,Second_Round_Wins,Sweet_Sixteen_Wins,Elite_Eight_Wins,Final_Four_Wins
0,44,141,343,156,90,349,100,51,200,77,...,266,44,296,75,0,0,0,0,0,0
1,278,177,162,70,119,192,272,64,22,46,...,131,162,63,51,0,0,0,0,0,0
2,66,185,36,184,200,304,132,76,320,150,...,27,275,339,142,0,0,0,0,0,0

In [21]:
def Sixth_Wins(row):
    if row > 5:
        result = '1'
    else:
        result = '0'
    return result

data_df['Championship_Wins'] = data_df['Tournament_Wins'].apply(Sixth_Wins)
data_df.head(30)

,Assists Per. Game Rank,Assist Turnover Ratio Rank,BlocksPerGame Rank,Field Goal % Rank,Field Goal % Defense Rank,Fouls Per Game Rank,Free Throw % Rank,Rebound Margin Rank,Scoring Defense Rank,Scoring Margin Rank,...,Turnover Margin Rank,Turnover Per Game Rank,Win-Loss Rank,Tournament_Wins,First_Round_Wins,Second_Round_Wins,Sweet_Sixteen_Wins,Elite_Eight_Wins,Final_Four_Wins,Championship_Wins
0,44,141,343,156,90,349,100,51,200,77,...,44,296,75,0,0,0,0,0,0,0
1,278,177,162,70,119,192,272,64,22,46,...,162,63,51,0,0,0,0,0,0,0
2,66,185,36,184,200,304,132,76,320,150,...,275,339,142,0,0,0,0,0,0,0
3,1,17,8,4,10,319,95,9,137,3,...,232,110,2,2,1,1,0,0,0,0
4,116,110,71,218,58,323,32,89,145,53,...,40,287,36,3,1,1,1,0,0,0
5,60,66,1,206,7,326,118,68,114,15,...,47,116,7,1,1,0,0,0,0,0
6,24,43,134,59,128,227,241,41,35,7,...,20,156,12,1,1,0,0,0,0,0
7,292,236,136,147,148,170,338,45,13,57,...,109,115,21,0,0,0,0,0,0,0
8,111,191,45,200,76,212,116,93,281,114,...,288,285,62,0,0,0,0,0,0,0
9,299,253,330,146,211,119,20,141,96,141,...,72,119,80,0,0,0,0,0,0,0
10,179,86,319,48,121,223,76,37,39,24,...,92,41,21,0,0,0,0,0,0,0
11,8,11,116,29,135,122,240,102,109,39,...,217,58,75,0,0,0,0,0,0,0
12,91,22,187,16,167,44,16,208,77,58,...,51,262,11,0,0,0,0,0,0,0
13,153,231,61,128,22,60,97,109,90,156,...,337,296,75,1,1,0,0,0,0,0
14,69,14,257,15,104,112,53,85,76,30,...,96,10,12,0,0,0,0,0,0,0
15,198,191,106,38,165,223,80,236,201,146,...,185,349,104,0,0,0,0,0,0,0
16,11,4,9,6,94,183,99,63,130,10,...,152,21,9,4,1,1,1,1,0,0
17,138,96,44,336,93,42,156,161,67,107,...,5,310,113,0,0,0,0,0,0,0
18,3,7,6,1,2,102,178,4,84,1,...,155,77,3,2,1,1,0,0,0,0
19,14,18,14,47,1,341,316,12,3,2,...,25,331,6,3,1,1,1,0,0,0
20,41,60,193,125,62,196,207,31,115,63,...,289,279,56,1,1,0,0,0,0,0
21,72,57,29,98,21,304,231,108,82,116,...,169,224,125,1,1,0,0,0,0,0
22,67,148,181,230,133,333,284,230,21,148,...,36,4,104,2,1,1,0,0,0,0
23,20,1,53,62,199,282,67,143,233,11,...,7,282,45,0,0,0,0,0,0,0
24,86,131,214,42,48,34,279,62,116,80,...,267,60,80,0,0,0,0,0,0,0
25,36,51,56,21,39,332,167,40,118,16,...,144,69,5,6,1,1,1,1,1,1
26,15,23,64,13,70,84,144,1,98,8,...,143,84,28,0,0,0,0,0,0,0
27,77,84,297,113,184,126,136,18,68,20,...,66,143,16,0,0,0,0,0,0,0
28,54,61,289,22,50,268,181,107,17,13,...,89,123,32,0,0,0,0,0,0,0
29,188,291,60,192,6,339,120,116,30,32,...,24,319,87,0,0,0,0,0,0,0

In [22]:
data_df.to_csv(r'/Users/bryanwenger/Desktop/Final_Project/March_Madness/Data_Creation/Bryan/wins_by_round.csv')

# Process with new First Round wins column to see if accuracy is improved

In [23]:
data_df.count()

Assists Per. Game Rank        674
Assist Turnover Ratio Rank    674
BlocksPerGame Rank            674
Field Goal % Rank             674
Field Goal % Defense Rank     674
Fouls Per Game Rank           674
Free Throw % Rank             674
Rebound Margin Rank           674
Scoring Defense Rank          674
Scoring Margin Rank           674
Scoring Offense Rank          674
Steals Per Game Rank          674
Three Pt FG Defense Rank      674
Three Pt FG % Rank            674
Three Pt FG Per Game Rank     674
Turnover Margin Rank          674
Turnover Per Game Rank        674
Win-Loss Rank                 674
Tournament_Wins               674
First_Round_Wins              674
Second_Round_Wins             674
Sweet_Sixteen_Wins            674
Elite_Eight_Wins              674
Final_Four_Wins               674
Championship_Wins             674
dtype: int64

In [24]:
data1_df = data_df
data1_df.drop(columns=['Tournament_Wins','Second_Round_Wins', 'Sweet_Sixteen_Wins', 'Elite_Eight_Wins', 'Final_Four_Wins', 'Championship_Wins'], inplace=True)
data1_df.dtypes

Assists Per. Game Rank         int64
Assist Turnover Ratio Rank     int64
BlocksPerGame Rank             int64
Field Goal % Rank              int64
Field Goal % Defense Rank      int64
Fouls Per Game Rank            int64
Free Throw % Rank              int64
Rebound Margin Rank            int64
Scoring Defense Rank           int64
Scoring Margin Rank            int64
Scoring Offense Rank           int64
Steals Per Game Rank           int64
Three Pt FG Defense Rank       int64
Three Pt FG % Rank             int64
Three Pt FG Per Game Rank      int64
Turnover Margin Rank           int64
Turnover Per Game Rank         int64
Win-Loss Rank                  int64
First_Round_Wins              object
dtype: object

In [25]:
y = data1_df["First_Round_Wins"]
X = data1_df.drop(columns="First_Round_Wins")

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(505, 18)

In [27]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=2000,
                                random_state=7)

In [28]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=2000, random_state=7)

In [29]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

   Prediction Actual
0           0      0
1           0      0
2           1      0
3           1      0
4           0      0
5           0      0
6           0      0
7           1      1
8           0      0
9           1      1
10          1      0
11          1      1
12          0      0
13          0      0
14          1      0
15          0      0
16          0      0
17          1      1
18          0      1
19          1      1

In [30]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.6390532544378699

In [31]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[40 33]
 [28 68]]

In [32]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.59      0.55      0.57        73
           1       0.67      0.71      0.69        96

    accuracy                           0.64       169
   macro avg       0.63      0.63      0.63       169
weighted avg       0.64      0.64      0.64       169

In [33]:
data2_df = pd.read_csv('/Users/bryanwenger/Desktop/Final_Project/March_Madness/Data_Creation/Bryan/wins_by_round.csv')

In [34]:
data2_df = data2_df[data2_df.First_Round_Wins != 0]

In [35]:
data2_df.drop(columns=['Tournament_Wins','First_Round_Wins', 'Sweet_Sixteen_Wins', 'Elite_Eight_Wins', 'Final_Four_Wins', 'Championship_Wins'], inplace=True)

In [36]:
y = data2_df["Second_Round_Wins"]
X = data2_df.drop(columns="Second_Round_Wins")

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(286, 19)

In [38]:
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=2000,
                                random_state=7)

In [39]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=2000, random_state=7)

In [40]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            1       1
1            1       1
2            1       1
3            0       1
4            0       1
5            0       0
6            0       1
7            1       1
8            1       1
9            1       0
10           0       1
11           1       0
12           1       1
13           0       0
14           1       1
15           1       0
16           0       0
17           1       0
18           1       0
19           1       1

In [41]:
print(accuracy_score(y_test, y_pred))

0.6145833333333334

In [42]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[34 17]
 [20 25]]

In [43]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.63      0.67      0.65        51
           1       0.60      0.56      0.57        45

    accuracy                           0.61        96
   macro avg       0.61      0.61      0.61        96
weighted avg       0.61      0.61      0.61        96

In [44]:
data3_df = pd.read_csv('/Users/bryanwenger/Desktop/Final_Project/March_Madness/Data_Creation/Bryan/wins_by_round.csv')

In [45]:
data3_df = data3_df[data3_df.Second_Round_Wins != 0]

In [46]:
data3_df.drop(columns=['Tournament_Wins','First_Round_Wins', 'Second_Round_Wins', 'Elite_Eight_Wins', 'Final_Four_Wins', 'Championship_Wins'], inplace=True)

In [47]:
y = data3_df["Sweet_Sixteen_Wins"]
X = data3_df.drop(columns="Sweet_Sixteen_Wins")

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(135, 19)

In [49]:
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=2000,
                                random_state=7)

In [50]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=2000, random_state=7)

In [51]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       1
1            0       1
2            1       1
3            1       0
4            0       0
5            1       1
6            0       0
7            1       1
8            1       1
9            0       0
10           1       1
11           1       1
12           1       1
13           0       0
14           1       1
15           0       0
16           1       1
17           1       1
18           0       1
19           0       0

In [52]:
print(accuracy_score(y_test, y_pred))

0.6666666666666666

In [53]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[14  8]
 [ 7 16]]

In [54]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.67      0.64      0.65        22
           1       0.67      0.70      0.68        23

    accuracy                           0.67        45
   macro avg       0.67      0.67      0.67        45
weighted avg       0.67      0.67      0.67        45

In [55]:
data4_df = pd.read_csv('/Users/bryanwenger/Desktop/Final_Project/March_Madness/Data_Creation/Bryan/wins_by_round.csv')

In [56]:
data4_df = data4_df[data4_df.Second_Round_Wins != 0]

In [57]:
data4_df.drop(columns=['Tournament_Wins','First_Round_Wins', 'Second_Round_Wins', 'Sweet_Sixteen_Wins', 'Final_Four_Wins', 'Championship_Wins'], inplace=True)

In [58]:
y = data4_df["Elite_Eight_Wins"]
X = data4_df.drop(columns="Elite_Eight_Wins")

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(135, 19)

In [60]:
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=2000,
                                random_state=7)

In [61]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=2000, random_state=7)

In [62]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       0
1            0       0
2            1       0
3            0       0
4            0       0
5            1       1
6            0       0
7            0       0
8            1       1
9            0       0
10           0       0
11           0       0
12           1       0
13           0       0
14           0       0
15           0       0
16           0       0
17           0       1
18           0       0
19           0       0

In [63]:
print(accuracy_score(y_test, y_pred))

0.7333333333333333

In [64]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[31  3]
 [ 9  2]]

In [65]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.78      0.91      0.84        34
           1       0.40      0.18      0.25        11

    accuracy                           0.73        45
   macro avg       0.59      0.55      0.54        45
weighted avg       0.68      0.73      0.69        45

In [66]:
data5_df = pd.read_csv('/Users/bryanwenger/Desktop/Final_Project/March_Madness/Data_Creation/Bryan/wins_by_round.csv')

In [67]:
data5_df = data5_df[data5_df.Second_Round_Wins != 0]

In [68]:
data5_df.drop(columns=['Tournament_Wins','First_Round_Wins', 'Second_Round_Wins', 'Sweet_Sixteen_Wins', 'Elite_Eight_Wins', 'Championship_Wins'], inplace=True)

In [69]:
y = data5_df["Final_Four_Wins"]
X = data5_df.drop(columns="Final_Four_Wins")

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(135, 19)

In [71]:
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=2000,
                                random_state=7)

In [72]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=2000, random_state=7)

In [73]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       1
1            0       0
2            0       1
3            0       1
4            0       0
5            0       0
6            0       0
7            0       0
8            0       0
9            0       0
10           0       1
11           0       0
12           0       0
13           0       0
14           0       0
15           0       0
16           0       1
17           0       0
18           0       0
19           0       0

In [74]:
print(accuracy_score(y_test, y_pred))

0.8666666666666667

In [75]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[39  0]
 [ 6  0]]

In [76]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.87      1.00      0.93        39
           1       0.00      0.00      0.00         6

    accuracy                           0.87        45
   macro avg       0.43      0.50      0.46        45
weighted avg       0.75      0.87      0.80        45

/Users/bryanwenger/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/bryanwenger/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/bryanwenger/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [77]:
data6_df = pd.read_csv('/Users/bryanwenger/Desktop/Final_Project/March_Madness/Data_Creation/Bryan/wins_by_round.csv')

In [78]:
data6_df = data6_df[data6_df.Second_Round_Wins != 0]

In [79]:
data6_df.drop(columns=['Tournament_Wins','First_Round_Wins', 'Second_Round_Wins', 'Sweet_Sixteen_Wins', 'Elite_Eight_Wins', 'Final_Four_Wins'], inplace=True)

In [80]:
y = data6_df["Championship_Wins"]
X = data6_df.drop(columns="Championship_Wins")

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(135, 19)

In [82]:
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=2000,
                                random_state=7)

In [83]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=2000, random_state=7)

In [84]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            1       0
1            0       0
2            1       1
3            0       0
4            1       0
5            0       1
6            0       0
7            0       1
8            0       0
9            0       0
10           0       0
11           0       0
12           0       0
13           0       0
14           0       0
15           0       0
16           0       0
17           0       0
18           0       0
19           0       0

In [85]:
print(accuracy_score(y_test, y_pred))

0.8666666666666667

In [86]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[38  4]
 [ 2  1]]

In [87]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.95      0.90      0.93        42
           1       0.20      0.33      0.25         3

    accuracy                           0.87        45
   macro avg       0.57      0.62      0.59        45
weighted avg       0.90      0.87      0.88        45